language: go
sudo: false
go:
- "1.10.x"
before_script:
  - go vet ./...
script:
 - "gofmt -s -d $(find . -type f -name '*.go') |& perl -pe 'END{exit($. > 0 ? 1 : 0)}'"
 - go test -v ./...
 - tests/all.bash
