language: go
sudo: false
go:
- "1.13.x"
install:
  - sudo apt-get install -y zsh
  - go get -v -t golang.org/x/lint/golint honnef.co/go/tools/cmd/...
  - go get -t ./...
before_script:
  # - go vet ./...
script:
 - ./scripts/presubmit.sh #presubmit
